# Generated by Django 5.1 on 2024-09-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monuments/'),
        ),
    ]
